name: ESP32-WROVER-B-N4R8 MicroPython Firmware

on:
  workflow_dispatch:

env:
  MICROPYTHON: micropython
  MICROPYTHON_REPO: https://github.com/micropython/micropython.git
  MICROPYTHON_VERSION: v1.23.0
  ESPIDF: esp-idf
  ESPIDF_REPO: https://github.com/espressif/esp-idf.git
  ESPIDF_BRANCH: v5.0.5
  ESP: esp

jobs:
  ESP32-WROVER-B-N4R8_MicroPython_Firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential git cmake python3.11-venv
          mkdir $ESP
          git clone --branch $MICROPYTHON_VERSION $MICROPYTHON_REPO $MICROPYTHON
          git clone --branch $ESPIDF_BRANCH $ESPIDF_REPO $ESPIDF

      - name: Install ESP-IDF
        run: |
          cd $ESPIDF
          ./install.sh
          source export.sh

      - name: Compile the firmware
        id: compile
        run: |
          cd $MICROPYTHON
          make -C mpy-cross
          cd ports/esp32
          make submodules
          make
          echo "status=success" >> $GITHUB_OUTPUT
          echo "COMPILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: Organize compiled firmware
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
          mv $MICROPYTHON/ports/esp32/build-ESP32_GENERIC/micropython.bin $ESP/ESP32-WROVER-B-N4R8_MicroPython-${{ env.MICROPYTHON_VERSION }}_${{ env.COMPILE_DATE }}.bin

      - name: Upload firmware to release
        if: steps.compile.outputs.status == 'success' && !cancelled()
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: $ESP/*
          asset_name: ${{ github.event.repository.name }}-${{ github.sha }}
          tag: ESP32-WROVER-B-N4R8_MicroPython-${{ env.MICROPYTHON_VERSION }}_${{ env.COMPILE_DATE }}
          body: |
            ### ESP32-WROVER-B-N4R8 MicroPython Firmware
          overwrite: true

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 2

      - name: Remove old releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 4
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
